### ISSUE TITLE
Coordinates are reversed

### ISSUE THREAD

**Issue by niclashedam** [lsv/rejseplan-php-api#8]
Flintholm St. returns the following coordnate
```
RejseplanApi\Coordinate {#573
  #latitude: 12.498656
  #longitude: 55.685432
}
```

That is incorrect.
Flintholm is located at long 12.498656 and lat 55.685432

**Comment by lsv** [comment]
Good catch - I always get those wrong, same with X and Y :)
- Ill just check if it has any influence around if I just "switch" them
